version: '3'

services:
  mood-tracker:
    build: .
    ports:
      - "6384:6384"
    volumes:
      - mood-data:/app/instance
    environment:
      - SUBJECT_NAME=Gabriel
    restart: unless-stopped

volumes:
  mood-data:
